/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IKlaySwapFactory,
  IKlaySwapFactoryInterface,
} from "../IKlaySwapFactory";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "inToken",
        type: "address",
      },
      {
        name: "inAmount",
        type: "uint256",
      },
      {
        name: "outToken",
        type: "address",
      },
      {
        name: "outAmountMin",
        type: "uint256",
      },
      {
        name: "path",
        type: "address[]",
      },
    ],
    name: "exchangeKctPos",
    outputs: [],
    payable: true,
    stateMutability: "payable",
    type: "function",
  },
];

export class IKlaySwapFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IKlaySwapFactoryInterface {
    return new utils.Interface(_abi) as IKlaySwapFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKlaySwapFactory {
    return new Contract(address, _abi, signerOrProvider) as IKlaySwapFactory;
  }
}
