/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IKronosStaking,
  IKronosStakingInterface,
} from "../IKronosStaking";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "_recipient",
        type: "address",
      },
    ],
    name: "claim",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "_amount",
        type: "uint256",
      },
      {
        name: "_recipient",
        type: "address",
      },
    ],
    name: "stake",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "_amount",
        type: "uint256",
      },
      {
        name: "_trigger",
        type: "bool",
      },
    ],
    name: "unstake",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [],
    name: "rebase",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IKronosStaking__factory {
  static readonly abi = _abi;
  static createInterface(): IKronosStakingInterface {
    return new utils.Interface(_abi) as IKronosStakingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKronosStaking {
    return new Contract(address, _abi, signerOrProvider) as IKronosStaking;
  }
}
